
datasets: ["topmed"]

# these are fixed files
#genome_bed: "files/hg38_clean.bed"
#blacklist: "files/hg38-blacklist.v2.bed"
#twobitgenome: "files/hg38.2bit"
#exome_pos:
#topmed_data: "raw_vcf/"
#coverage: "coverage/"

# hyperparameters i want to try out
allelefrequency: [0.0001]
depth: [10] # maybe adding this later
#methylation_data: "methylation_data/ENCFF926RAG.bed"
#replication_time: "replicationtime_data/reptime.bed"
#recombination: "recombination/recom_rate.bed"

chromosomes: [chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,
              chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,
              chr21,chr22]


chromosome_length: {chr1: 248956422, chr2: 242193529, 
                    chr3: 198295559, chr4: 190214555,
                    chr5: 181538259, chr6: 170805979,
                    chr7: 159345973, chr8: 145138636,
                    chr9: 138394717, chr10: 133797422,
                    chr11: 135086622, chr12: 133275309,
                    chr13: 114364328, chr14: 107043718,
                    chr15: 101991189, chr16: 90338345,
                    chr17: 83257441, chr18: 80373285,
                    chr19: 58617616, chr20: 64444167,
                    chr21: 46709983, chr22: 50818468,
                    chrX: 156040895, chrY: 57227415}

window_size_kb: [10]

#kmer_indels: [4,6] #,6, 8, 10, 2]

NumberWithDepth: [90]

# size_partition: [11,23,40] # make it in such a way there is a upper and lower limit to t

# complex_structure: [APR, DR, GQ, IR, MR, STR, Z]